channels:
- conda-forge
dependencies:
- python=3.6.2
- pip=20.2.4
- pip:
  - azureml-core==1.26.0
  - azureml-defaults==1.26.0
  - azureml-telemetry==1.26.0
  - azureml-train-restclients-hyperdrive==1.26.0
  - azureml-train-core==1.26.0
  - cmake==3.18.2
  - torch==1.6.0
  - torchvision==0.5.0
  - mkl==2018.0.3
  - horovod==0.20.0
  - tensorboard==1.14.0
  - future==0.17.1
  - matplotlib==3.3.4
name: azureml_15a1ed1df60c62eb2ab6b34ff768e80f
